# https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action
name: Setup Node and pnpm
inputs:
  node-version:
    required: true
    default: 16
  registry-url:
    required: true
    default: "https://registry.npmjs.org"
  pnpm-version:
    required: true
    default: 7
  run-install:
    required: true
    default: true
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: ${{ inputs.pnpm-version }}

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: "pnpm"

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - run: pnpm install --frozen-lockfile
      shell: bash
      if: ${{ inputs.run-install == 'true' }}
