name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["16"]
        os: [ubuntu-latest]
    name: Test with Node v${{ matrix.node }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup PNPM
        uses: ./.github/actions/pnpm
        with:
          run-install: true
      - run: pnpm test

  changeset:
    name: Check if version upgrade
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PNPM
        uses: ./.github/actions/pnpm
        with:
          run-install: true
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Echo if a publish happens
        if: steps.changesets.outputs.published == 'true'
        # You can do something when a publish happens.
        run: echo "A new version of ${GITHUB_REPOSITORY} was published!"
